apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: default
  labels:
    app: front-end
spec:
  type: ClusterIP
  selector:
    app: front-end
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 3000