apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: default
  labels:
    app: front-end
    role: public
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
      