apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: k8s-master:5000/front-end:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 3000
          command: [ "npm", "run", "dev", "--", "-H", "0.0.0.0" ]
          env:
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: front-end-secrets
                  key: DATABASE_PASS
          volumeMounts:
            - name: config-volume
              mountPath: /config/.env.template
              subPath: .env.template
            - name: compression-volume
              mountPath: /mnt/compression-queue
      volumes:
        - name: config-volume
          configMap:
            name: env-template
        - name: compression-volume
          persistentVolumeClaim:
            claimName: pvc-compression-queue