apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  selector:
    app: front-end
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
    - name: metrics
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer