apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: backend
      role: metrics
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /api/metrics
      interval: 15s