apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: front-end-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: front-end
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: metrics
      path: /api/metrics
      interval: 15s