apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: front-end-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: front-end
      role: metrics
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /api/metrics
      interval: 15s
      basicAuth:
        username:
          name: front-end-metrics-auth
          key: username
        password:
          name: front-end-metrics-auth
          key: password
