apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: watchdog-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: watchdog
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s