apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mock-deployment
  labels:
    app: backend-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-mock
  template:
    metadata:
      labels:
        app: backend-mock
    spec:
      containers:
        - name: backend-mock
          image: k8s-master:5000/backend-mock:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: front-end-secrets
                  key: DATABASE_PASS
          volumeMounts:
            - name: compression-volume
              mountPath: /mnt/compression-queue
      volumes:
        - name: config-volume
          configMap:
            name: front-end-env-template
        - name: compression-volume
          persistentVolumeClaim:
            claimName: pvc-compression-queue