{
 "title": "Backend",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Jobs Procesed in secound",
   "type": "stat",
   "description": "Time spent processing compression jobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(compression_job_processing_seconds_bucket[5m])) by (le, file_type))",
     "legendFormat": "{{file_type}}"
    }
   ]
  },
  {
   "title": "Total Jobs Processed Success",
   "type": "gauge",
   "description": "Total number of compression jobs processed",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(compression_jobs_processed_total{status=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs by file type",
   "type": "piechart",
   "description": "Current size of the compression queue",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(compression_jobs_processed_total) by (file_type)",
     "legendFormat": "{{file_type}}"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(compression_jobs_processed_total{status=\"failed\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(compression_jobs_processed_total{status=\"failed\"}) by (file_type) / sum(compression_jobs_processed_total) by (file_type) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Status",
   "type": "state-timeline",
   "description": "Status of the compression worker (1=running, 0=stopped)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "compression_worker_status{endpoint=\"metrics\"}",
     "legendFormat": "{{instance}} | | {{pod}}"
    }
   ]
  }
 ]
}