{
 "title": "Watchdog Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Overdue 5 m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_overdue_jobs_total[5m]))"
    }
   ]
  },
  {
   "title": "Errors 5 m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_errors_total[5m]))"
    }
   ]
  },
  {
   "title": "Failed 5 m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_failed_jobs_total[5m]))"
    }
   ]
  },
  { "title": "Overdue Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Overdue 5 m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_overdue_jobs_total[5m]))"
    }
   ]
  },
  {
   "title": "Overdue 15 m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_overdue_jobs_total[15m]))"
    }
   ]
  },
  {
   "title": "Overdue 1 h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_overdue_jobs_total[1h]))"
    }
   ]
  },
  {
   "title": "Overdue 24 h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_overdue_jobs_total[24h]))"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Errors 5 m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_errors_total[5m]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Errors 15 m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_errors_total[15m]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Errors 1 h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_errors_total[1h]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Errors 24 h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_errors_total[24h]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  { "title": "Failed Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Failed 5 m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_failed_jobs_total[5m]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Failed 15 m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_failed_jobs_total[15m]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Failed 1 h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_failed_jobs_total[1h]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Failed 24 h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "floor(increase(watchdog_failed_jobs_total[24h]))",
     "legendFormat": "{{stage}}"
    }
   ]
  }
 ]
}