apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-tools
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-tools
  template:
    metadata:
      labels:
        app: debug-tools
    spec:
      containers:
        - name: debug-tools
          image: k8s-master:5000/debug-tools:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "sleep infinity"]