name: Deploy Redis

on:
  push:
    branches:
      - dawid-branch

jobs:
  deploy:
    if: false
    runs-on: [self-hosted, dawid-runner]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_MATRIX }}" > $HOME/.kube/config

      - name: Apply Redis Deployment
        working-directory: redis
        run: |
          kubectl apply -f redis-deployment.yaml

      - name: Apply Redis Service
        working-directory: redis
        run: |
          kubectl apply -f redis-service.yaml

      - name: Check rollout status
        run: |
          kubectl rollout restart deployment/redis
          kubectl rollout status deployment/redis