name: Deploy NFS

on:
  push:
    branches:
      - michal-branch

jobs:
  deploy-nfs:
    if: false
    runs-on: [self-hosted, michal-runner]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CREEPERASEK }}" > $HOME/.kube/config

      - name: Deploy NFS storage
        run: |
          kubectl apply -f nfs/pv-nfs.yaml
          kubectl apply -f nfs/pvc-nfs.yaml