name: Deploy Debug Tools

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, michal-runner]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image debug-tools
        run: |
          docker build -t k8s-master:5000/debug-tools:${{ github.sha }} ./debug-pod

      - name: Push Docker image debug-tools
        run: |
          docker push k8s-master:5000/debug-tools:${{ github.sha }}

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CREEPERASEK }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f debug-pod/debug-deployment.yaml
          kubectl set image deployment/debug-tools debug-tools=k8s-master:5000/debug-tools:${{ github.sha }}
          kubectl rollout restart deployment/debug-tools
          kubectl rollout status deployment/debug-tools
