name: Deploy Nginx

on:
  push:
    branches:
      - dawid-branch

jobs:
  deploy:
    runs-on: [self-hosted, dawid]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t k8s-master:5000/my-nginx:${{ github.sha }} ./test

      - name: Push Docker image
        run: |
          docker push k8s-master:5000/my-nginx:${{ github.sha }}

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f test/nginx-deployment.yaml
          kubectl apply -f test/nginx-service.yaml
          kubectl set image deployment/nginx-deployment nginx=k8s-master:5000/my-nginx:${{ github.sha }}
          kubectl rollout status deployment/nginx-deployment
