name: Deploy CronJobs

on:
  push:
    branches:
      - michal-branch

jobs:
  deploy-cronjobs:
    if: true
    runs-on: [self-hosted, michal-runner]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CREEPERASEK }}" > $HOME/.kube/config

      - name: Deploy CronJobs
        run: |
          kubectl apply -f cronjobs/