name: Deploy Debug Tools

on:
  workflow_dispatch:

jobs:
  deploy-debug:
    runs-on: [self-hosted, dawid]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy debug pod
        run: kubectl apply -f debug-pod/debug-deployment.yaml