name: Deploy Observability Resources

on:
  push:
    branches:
      - dawid-branch
    paths:
      - 'observability/**'

jobs:
  deploy-observability:
    runs-on: [self-hosted, dawid-runner]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_MATRIX }}" > $HOME/.kube/config

      - name: Deploy all observability resources
        run: |
          kubectl apply -R -f observability/