name: Deploy Test Image

on:
  push:
    branches:
      - mateusz-branch

jobs:
  deploy:
    if: false
    runs-on: [self-hosted, dawid-runner]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t k8s-master:5000/front-end:${{ github.sha }} ./front-end

      - name: Push Docker image
        run: |
          docker push k8s-master:5000/front-end:${{ github.sha }}

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DAWID }}" > $HOME/.kube/config

      - name: Deploy NFS storage (PV & PVC)
        run: |
          kubectl apply -f test/pv-nfs.yaml
          kubectl apply -f test/pvc-nfs.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f front-end/front-end-deployment.yaml
          kubectl apply -f front-end/front-end-service.yaml
          kubectl rollout status deployment/front-end-deployment
