name: Deploy Test Image

on:
  push:
    branches:
      - michal-branch

jobs:
  deploy:
    runs-on: [self-hosted, michal-runner]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t k8s-master:5000/my-nginx:${{ github.sha }} ./test

      - name: Push Docker image
        run: |
          docker push k8s-master:5000/my-nginx:${{ github.sha }}

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy NFS storage (PV & PVC)
        run: |
          kubectl apply -f test/pv-nfs.yaml
          kubectl apply -f test/pvc-nfs.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f test/nginx-deployment.yaml
          kubectl apply -f test/nginx-service.yaml
          kubectl set image deployment/nginx-deployment nginx=k8s-master:5000/my-nginx:${{ github.sha }}
          kubectl rollout status deployment/nginx-deployment
          